// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyxlRUxxDTTuYtRt3gwG7c1N4gsZX6whA',
    appId: '1:508684511968:web:922f88caffb2b47c047e85',
    messagingSenderId: '508684511968',
    projectId: 'nutrisense-6df8a',
    authDomain: 'nutrisense-6df8a.firebaseapp.com',
    storageBucket: 'nutrisense-6df8a.firebasestorage.app',
    measurementId: 'G-22M19QN6H9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7YEaYTHNei14xvJsnObrNr-JE4mnDsFU',
    appId: '1:508684511968:android:a20eae41c4f59964047e85',
    messagingSenderId: '508684511968',
    projectId: 'nutrisense-6df8a',
    storageBucket: 'nutrisense-6df8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnAeHOGh79q51jTTaCkR95k7S19PPgLsY',
    appId: '1:508684511968:ios:3a241585c9c28aed047e85',
    messagingSenderId: '508684511968',
    projectId: 'nutrisense-6df8a',
    storageBucket: 'nutrisense-6df8a.firebasestorage.app',
    iosBundleId: 'com.example.nutrisense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnAeHOGh79q51jTTaCkR95k7S19PPgLsY',
    appId: '1:508684511968:ios:3a241585c9c28aed047e85',
    messagingSenderId: '508684511968',
    projectId: 'nutrisense-6df8a',
    storageBucket: 'nutrisense-6df8a.firebasestorage.app',
    iosBundleId: 'com.example.nutrisense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyxlRUxxDTTuYtRt3gwG7c1N4gsZX6whA',
    appId: '1:508684511968:web:446c63162d732a75047e85',
    messagingSenderId: '508684511968',
    projectId: 'nutrisense-6df8a',
    authDomain: 'nutrisense-6df8a.firebaseapp.com',
    storageBucket: 'nutrisense-6df8a.firebasestorage.app',
    measurementId: 'G-R1QRYGTW3S',
  );
}
